makeSummaryTable <- function(st, et, vs, ad, leg, ship){
  
  #' makeSummaryTable
  #' 
  #' description: Summarize effort track distance and sightings data and display
  #' in a flex table which can be saved and uploaded to the website. Relies on 
  #' previously parsed track and visual sighting data
  #' 
  #' Sightings
  #' of unidentified small, medium, and large dolphins and unidentified dolphins were combined into a single category, “unidentified dolphins,” for detection function and abundance estimation. Likewise, sightings of unidentified small and large whales and unidentified
  #' whales and cetaceans were combined into the category “unidentified cetaceans.”
  #' 
  #' author: Selene Fregosi selene.fregosi [at] noaa.gov
  #' date: 30 June 2023
  #'
  #' @param st 'summary table' data.frame containing summary data for previous 
  #' days and legs
  #' @param et 'effort track' variable with on effort segment times, locations, 
  #' durations, distances, and sea state; generated by 'parseTrack.R'
  #' @param vs 'visual sightings' variable with species code, effort information, 
  #' time and location data; generated by 'extractVisualSightings.R'
  #' @param ad 'acoustic detections' variable with species code, generated by 
  #' 'extractAcousticDetections.R'
  #' @param leg string for leg number set in beginning of run.R
  #' @param ship string for ship set in beginning of run.R
  #' 
  #' @return a list 'lt' with st - a data.frame summary table and ft - a flextable 
  #' @export
  #'
  #' @examples
  #'
  
  # if summary table has not been created before, make an empty one
  if (nrow(st) == 0){
  legList = c('Leg 01 OES', 'Leg 02 OES', 'Leg 03 OES', 'Leg 04 OES', 'Leg 05 OES', 
              'Leg 01 LSK', 'Leg 02 LSK', 'Total')
  st = data.frame(leg_ship = legList, 
                  days = integer(length(legList)), 
                  #segments = integer(length(legList)), 
                  dist = integer(length(legList)), 
                  spVis = integer(length(legList)), 
                  spPam = integer(length(legList)))
  st[st == 0] <- NA
  }
  
  # define row indices for this leg and ship
  if (leg == '01' && ship == 'OES'){
    idx = 1
  }else if (leg == '02' && ship == 'OES'){
    idx = 2
  }else if (leg == '03' && ship == 'OES'){
    idx = 3
  }else if (leg == '04' && ship == 'OES'){
    idx = 4
  }else if (leg == '05' && ship == 'OES'){
    idx = 5
  }else if (leg == '01' && ship == 'LSK'){
    idx = 6
  }else if (leg == '02' && ship == 'LSK'){
    idx = 7
  }else if (leg == '00'){
    # testing..
    idx = 0
  }
  
  # calculate summary stats
  monthdays = format(et$mDateTime, format = '%m%d')
  st$days[idx] = length(unique(monthdays))
  # st$segments[idx] = length(et$segnum)
  st$dist[idx] = sum(et$dist)
  st$spVis[idx] = length(vs$SpCode)
  st$spPam[idx] = NA
  
  # sum the legs
  st$days[8] = sum(as.integer(st$days[1:7]), na.rm = TRUE)
  # st$segments[8] = sum(as.integer(st$segments[1:7]), na.rm = TRUE)
  st$dist[8] = round(sum(as.double(st$dist[1:7]), na.rm = TRUE))
  st$spVis[8] = sum(as.integer(st$spVis[1:7]), na.rm = TRUE)
  st$spPam[8] = sum(as.integer(st$spPam[1:7]), na.rm = TRUE)
  
  # View(st)

  # create nicely formated flextable
  ft = flextable(st)
  ft = theme_vanilla(ft)
  ft = set_header_labels(ft, leg_ship = 'Leg and Ship', days = 'Days at Sea',
                         segments = 'Segments', dist = 'Distance [km]', 
                         spVis = 'Visual Sightings', 
                         spPam = 'Acoustic Detections')
  # ft = add_header_row(x = ft, values = c('', 'Effort', 'Species'), colwidths = c(2, 2, 2))

  ft = width(ft, 1, width = 1.1)
  # ft = width(ft, 2, width = 0.6)
  ft = width(ft, c(2,3), width = 0.8)
  ft = width(ft, c(4,5), width = 1.2)
  ft = align(ft, j = c(2,3,4,5), align = 'center')
  ft = align(ft, align = 'center', part = 'header')
  ft = colformat_double(ft, j = 3, digits = 1)
  # align_text_col(ft, align = "center", header = TRUE, footer = TRUE)
  # ft = set_table_properties(ft,align = 'center')
  # ft = ft |>
  #   separate_header() |>
  #   align(align = 'center', part = 'all') |>
  #   autofit()
  # ft
  
  lt = list(st = st, ft = ft)
  
  return(lt)
  
}
