makeSummaryTable <- function(st, et, vs, ad, shipCode, leg){
  
  #' makeSummaryTable
  #' 
  #' @description Summarize effort track distance and sightings data and display
  #' in a flex table which can be saved and uploaded to the website. Relies on 
  #' previously parsed track and visual sighting data
  #' 
  #' author: Selene Fregosi selene.fregosi [at] noaa.gov
  #' date: 13 October 2023
  #'
  #' @param st 'summary table' data.frame containing summary data for previous 
  #' days and legs
  #' @param et 'effort track' variable with on effort segment times, locations, 
  #' durations, distances, and sea state; generated by 'parseTrack.R'
  #' @param vs 'visual sightings' variable with species code, effort information, 
  #' time and location data; generated by 'extractVisualSightings.R'
  #' @param ad 'acoustic detections' variable with species code, generated by 
  #' 'extractAcousticDetections.R'
  #' @param shipCode string for ship set in beginning of run.R - can have length > 1
  #' @param leg string for leg number set in beginning of run.R - can have length > 1
  #' 
  #' @return a list 'lt' with st - a data.frame summary table and ft - a flextable 
  #'
  #' @examples
  #'
  #'#######################################################################

  # if summary table has not been created before, make an empty one
  if (nrow(st) == 0){
    shipList = c('Sette', 'Sette', 'Sette', 'Sette', 'Sette', 
                 'Lasker', 'Lasker', '')
    legList = c(', Leg 1', ', Leg 2', ', Leg 3', ', Leg 4', ', Leg 5', 
                ', Leg 1', ', Leg 2', 'Total')
    # legList = c('Sette Leg 1', 'Sette Leg 2', 'Sette Leg 3', 'Sette Leg 4', 
    #             'Sette Leg 5', 'Lasker Leg 1', 'Lasker Leg 2', 'Total')
    st = data.frame(ship = shipList, 
                    leg = legList, 
                    days = integer(length(legList)), 
                    #segments = integer(length(legList)), 
                    dist = integer(length(legList)), 
                    spVis = integer(length(legList)), 
                    spPam = integer(length(legList))
    )
    st[st == 0] <- NA
  }
  
  
  for (s in 1:length(shipCode)){
    # define row indices for this leg and ship
    if (leg[s] == '1' & shipCode[s] == 'OES'){
      idx = 1
    }else if (leg[s] == '2' & shipCode[s] == 'OES'){
      idx = 2
    }else if (leg[s] == '3' & shipCode[s] == 'OES'){
      idx = 3
    }else if (leg[s] == '4' & shipCode[s] == 'OES'){
      idx = 4
    }else if (leg[s] == '5' & shipCode[s] == 'OES'){
      idx = 5
    }else if (leg[s] == '1' & shipCode[s] == 'LSK'){
      idx = 6
    }else if (leg[s] == '2' & shipCode[s] == 'LSK'){
      idx = 7
    }else if (leg[s] == '0'){
      # testing..
      idx = 0
    }
    
    # calculate summary stats
    et$monthdays = format(et$mDateTime, format = '%m%d')
    st$days[idx] = length(unique(et$monthdays[
      which(et$leg == leg[s] & et$shipCode == shipCode[s])]))
    # st$segments[idx] = length(et$segnum)
    st$dist[idx] = sum(et$dist[which(et$leg == leg[s] & 
                                       et$shipCode == shipCode[s])])
    st$spVis[idx] = length(vs$SpCode[which(vs$leg == leg[s] & 
                                             vs$shipCode == shipCode[s])])
    if (!is.null(ad)){
      st$spPam[idx] = length(ad$sp_map[which(ad$leg == leg[s] &
                                               ad$shipCode == shipCode[s])])
    }
  }
  
  # sum the legs
  st$days[8] = sum(as.integer(st$days[1:7]), na.rm = TRUE)
  # st$segments[8] = sum(as.integer(st$segments[1:7]), na.rm = TRUE)
  st$dist[8] = sum(as.double(st$dist[1:7]), na.rm = TRUE)
  st$spVis[8] = sum(as.integer(st$spVis[1:7]), na.rm = TRUE)
  st$spPam[8] = sum(as.integer(st$spPam[1:7]), na.rm = TRUE)
  
  # View(st)
  
  
  # create nicely formated flextable
  # ft = flextable::flextable(st, col_keys = c('Ship Leg', 'Days at Sea', 
  #                                            'Distance [km]', 'Visual Sightings',
  #                                            'Acoustic Detections')) 
  ft = flextable::flextable(st, col_keys = c('dummy', 'days', 'dist', 'spVis', 
                                             'spPam')) %>% 
    flextable::compose(j = 'dummy', value = flextable::as_paragraph(
      flextable::as_i(st$ship), st$leg))
  
  ft = flextable::theme_vanilla(ft)
  ft = flextable::set_header_labels(ft, dummy = 'Ship, Leg', days = 'Days at Sea',
                                    segments = 'Segments', dist = 'Distance [km]', 
                                    spVis = 'Visual Sightings', 
                                    spPam = 'Acoustic Detections'
  )
  # ft = add_header_row(x = ft, values = c('', 'Effort', 'Species'), colwidths = c(2, 2, 2))
  
  
  # limit significant digits
  ft = flextable::colformat_double(ft, j = 3, digits = 1)
  
  # define column widths and center align
  ft = flextable::width(ft, 1, width = 1.1)
  # ft = width(ft, 2, width = 0.6)
  ft = flextable::width(ft, c(2,3), width = 0.8)
  # ft = flextable::width(ft, c(4), width = 1.2)
  ft = flextable::width(ft, c(4,5), width = 1.2)
  # ft = flextable::align(ft, j = c(2,3,4), align = 'center')
  ft = flextable::align(ft, j = c(2,3,4,5), align = 'center')
  ft = flextable::align(ft, j = 1, align = 'right')
  ft = flextable::align(ft, align = 'center', part = 'header')
  
  # change borders and text color
  # relevant web colors
  purp = '#7F7FFF'
  wht = 'white'
  grn = '#93D500'
  teal = '#57b8E0'
  bg = '#373737'
  ltgry = '#D0D0D0'
  
  # body borders
  bd_thin = officer::fp_border(color = wht, width = 0.6)
  ft = flextable::hline(ft, part = 'body', border = bd_thin)
  # header/footer borders
  bd_thick = officer::fp_border(color = purp, width = 2)
  ft = flextable::hline_top(ft, part = 'header', border = bd_thick)
  ft = flextable::hline_bottom(ft, part = 'header', border = bd_thick)
  ft = flextable::hline_bottom(ft, part = 'body', border = bd_thick)
  # totals border
  bd_med = officer::fp_border(color = purp, width = 1)
  ft = flextable::hline(ft, i = 7, border = bd_med)
  
  # text colors
  ft = flextable::color(ft, color = ltgry, part = 'body')
  ft = flextable::color(ft, i = 8, color = purp) # Totals row
  ft = flextable::bold(ft, i = 8) # totals row
  ft = flextable::color(ft, color = teal, part = 'header')
  # ft = flextable::bg(ft, bg = bg, part = 'all')
  
  ft = flextable::add_footer_lines(ft, values = paste0('Last Updated: ', Sys.Date()))
  ft = flextable::color(ft, color = ltgry, part = 'footer')
  ft = flextable::fontsize(ft, size = 8, part = 'footer')
  # ft
  
  lt = list(st = st, ft = ft)
  
  return(lt)
  
}
